version: 2.1

jobs:
  build:
    docker:
     - image: cimg/node:20.12.2
    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "96:3e:f1:86:86:cd:bc:a1:2f:1d:47:e2:a8:fa:c3:de"

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            - v2-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: 
          name: Build package
          command: npm run build
        
      - run:
          name: Run tests
          command: npm test

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish to npm
          command: |
            if [[ "${CIRCLE_BRANCH}" == "main" || "${CIRCLE_BRANCH}" == "prerelease" ]]; then
              npm publish
            fi

      # Uncomment below to deploy Storybook on master
      # - run:
      #     name: Deploy Storybook
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         npm run deploy-storybook --ci
      #       fi
