version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "96:3e:f1:86:86:cd:bc:a1:2f:1d:47:e2:a8:fa:c3:de"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: build and test
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: publish to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm publish
            fi
      - run:
          name: deploy storybook
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run deploy-storybook --ci
            fi
