version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a5:ed:fb:90:cd:61:8f:85:5d:a2:58:84:3c:18:6c:ac"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: build and test
          command: npm run build
  
      - run:
          name: publish to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm publish --dry-run
            fi
      - run:
          name: deploy storybook
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run deploy-storybook --ci
            fi
